### ISSUE TITLE
Create configuration structure

### ISSUE THREAD

**Issue by blalhu** [blalhu/symfony-openapi-annotation-validator-bundle#11]
Mimic in php a config according to this [article](https://symfony.com/doc/2.x/bundles/configuration.html#processing-the-configs-array) whith the following structure:

```yaml
pelso_open_api_validator_bundle:
    interceptor: ~
    validator: ~
    definition_provider_collection: ~
    openapi_provider_list: []
    openapi_yaml_list: [] 
    openapi_json_list: []
```
